import type { FilamentColor, FilamentCategory } from './types';

const DEFAULT_BRAND = 'Bambu Lab';

// All known Bambu Lab color names, for the "add color" dropdown
export const KNOWN_COLOR_NAMES = [
  'White', 'Ivory White', 'Cream', 'Beige',
  'Lemon Yellow', 'Yellow', 'Gold', 'Orange', 'Coral',
  'Red', 'Dark Red', 'Pink', 'Magenta',
  'Purple', 'Violet',
  'Navy', 'Dark Blue', 'Blue', 'Sky Blue', 'Cyan',
  'Teal', 'Jade', 'Bambu Green', 'Green', 'Dark Green', 'Olive', 'Mint',
  'Brown', 'Dark Brown',
  'Silver', 'Copper', 'Bronze', 'Rose Gold',
  'Light Grey', 'Grey', 'Dark Grey', 'Charcoal', 'Black',
  'Transparent', 'Natural',
];

interface ColorDef { name: string; hex: string; category: FilamentCategory }

const COLOR_DEFS: ColorDef[] = [
  // ── PLA Basic ────────────────────────────────────────────────
  { name: 'White',       hex: '#F8F8F8', category: 'PLA Basic' },
  { name: 'Ivory White', hex: '#F5F0E8', category: 'PLA Basic' },
  { name: 'Cream',       hex: '#FFFACD', category: 'PLA Basic' },
  { name: 'Beige',       hex: '#F2E2C4', category: 'PLA Basic' },
  { name: 'Lemon Yellow',hex: '#FFF44F', category: 'PLA Basic' },
  { name: 'Yellow',      hex: '#FFD700', category: 'PLA Basic' },
  { name: 'Gold',        hex: '#D4AF37', category: 'PLA Basic' },
  { name: 'Orange',      hex: '#FF8C00', category: 'PLA Basic' },
  { name: 'Coral',       hex: '#FF6B6B', category: 'PLA Basic' },
  { name: 'Red',         hex: '#DC143C', category: 'PLA Basic' },
  { name: 'Dark Red',    hex: '#8B0000', category: 'PLA Basic' },
  { name: 'Pink',        hex: '#FF69B4', category: 'PLA Basic' },
  { name: 'Magenta',     hex: '#C71585', category: 'PLA Basic' },
  { name: 'Purple',      hex: '#7B2D8B', category: 'PLA Basic' },
  { name: 'Violet',      hex: '#8A2BE2', category: 'PLA Basic' },
  { name: 'Navy',        hex: '#001F5B', category: 'PLA Basic' },
  { name: 'Dark Blue',   hex: '#00008B', category: 'PLA Basic' },
  { name: 'Blue',        hex: '#1E6FCC', category: 'PLA Basic' },
  { name: 'Sky Blue',    hex: '#87CEEB', category: 'PLA Basic' },
  { name: 'Cyan',        hex: '#00BFFF', category: 'PLA Basic' },
  { name: 'Teal',        hex: '#008080', category: 'PLA Basic' },
  { name: 'Jade',        hex: '#00A36C', category: 'PLA Basic' },
  { name: 'Bambu Green', hex: '#1DB954', category: 'PLA Basic' },
  { name: 'Green',       hex: '#228B22', category: 'PLA Basic' },
  { name: 'Dark Green',  hex: '#006400', category: 'PLA Basic' },
  { name: 'Olive',       hex: '#808000', category: 'PLA Basic' },
  { name: 'Mint',        hex: '#98FF98', category: 'PLA Basic' },
  { name: 'Brown',       hex: '#795548', category: 'PLA Basic' },
  { name: 'Dark Brown',  hex: '#4E2A04', category: 'PLA Basic' },
  { name: 'Silver',      hex: '#C0C0C0', category: 'PLA Basic' },
  { name: 'Light Grey',  hex: '#D3D3D3', category: 'PLA Basic' },
  { name: 'Grey',        hex: '#808080', category: 'PLA Basic' },
  { name: 'Dark Grey',   hex: '#555555', category: 'PLA Basic' },
  { name: 'Charcoal',    hex: '#36454F', category: 'PLA Basic' },
  { name: 'Black',       hex: '#1A1A1A', category: 'PLA Basic' },

  // ── PLA Matte ────────────────────────────────────────────────
  // Matte finish — slightly warmer/more muted tones
  { name: 'White',       hex: '#F2F0EC', category: 'PLA Matte' },
  { name: 'Ivory White', hex: '#EDE8DE', category: 'PLA Matte' },
  { name: 'Beige',       hex: '#E8D8B8', category: 'PLA Matte' },
  { name: 'Lemon Yellow',hex: '#F0E860', category: 'PLA Matte' },
  { name: 'Yellow',      hex: '#E8C800', category: 'PLA Matte' },
  { name: 'Orange',      hex: '#E07800', category: 'PLA Matte' },
  { name: 'Coral',       hex: '#E05858', category: 'PLA Matte' },
  { name: 'Red',         hex: '#C01030', category: 'PLA Matte' },
  { name: 'Dark Red',    hex: '#780010', category: 'PLA Matte' },
  { name: 'Pink',        hex: '#E05890', category: 'PLA Matte' },
  { name: 'Magenta',     hex: '#A80060', category: 'PLA Matte' },
  { name: 'Purple',      hex: '#602070', category: 'PLA Matte' },
  { name: 'Navy',        hex: '#101840', category: 'PLA Matte' },
  { name: 'Blue',        hex: '#1858A8', category: 'PLA Matte' },
  { name: 'Sky Blue',    hex: '#6898C0', category: 'PLA Matte' },
  { name: 'Cyan',        hex: '#00A0C0', category: 'PLA Matte' },
  { name: 'Teal',        hex: '#006060', category: 'PLA Matte' },
  { name: 'Jade',        hex: '#008858', category: 'PLA Matte' },
  { name: 'Green',       hex: '#187018', category: 'PLA Matte' },
  { name: 'Dark Green',  hex: '#005000', category: 'PLA Matte' },
  { name: 'Olive',       hex: '#606000', category: 'PLA Matte' },
  { name: 'Brown',       hex: '#604030', category: 'PLA Matte' },
  { name: 'Light Grey',  hex: '#C0BEB8', category: 'PLA Matte' },
  { name: 'Grey',        hex: '#707068', category: 'PLA Matte' },
  { name: 'Dark Grey',   hex: '#404038', category: 'PLA Matte' },
  { name: 'Charcoal',    hex: '#282828', category: 'PLA Matte' },
  { name: 'Black',       hex: '#141414', category: 'PLA Matte' },

  // ── PLA Silk ─────────────────────────────────────────────────
  { name: 'Gold',        hex: '#D4A017', category: 'PLA Silk' },
  { name: 'Silver',      hex: '#C8CDD2', category: 'PLA Silk' },
  { name: 'Copper',      hex: '#B87333', category: 'PLA Silk' },
  { name: 'Bronze',      hex: '#8C6A30', category: 'PLA Silk' },
  { name: 'Rose Gold',   hex: '#C9897A', category: 'PLA Silk' },
  { name: 'White',       hex: '#EEF0F4', category: 'PLA Silk' },
  { name: 'Black',       hex: '#2A2A2E', category: 'PLA Silk' },
  { name: 'Red',         hex: '#CC2030', category: 'PLA Silk' },
  { name: 'Pink',        hex: '#E06080', category: 'PLA Silk' },
  { name: 'Purple',      hex: '#7030A0', category: 'PLA Silk' },
  { name: 'Blue',        hex: '#2050CC', category: 'PLA Silk' },
  { name: 'Cyan',        hex: '#00A8C8', category: 'PLA Silk' },
  { name: 'Green',       hex: '#20A040', category: 'PLA Silk' },
  { name: 'Orange',      hex: '#E07010', category: 'PLA Silk' },

  // ── PETG Basic ───────────────────────────────────────────────
  { name: 'White',       hex: '#F8F8F8', category: 'PETG Basic' },
  { name: 'Yellow',      hex: '#FFD700', category: 'PETG Basic' },
  { name: 'Orange',      hex: '#FF8C00', category: 'PETG Basic' },
  { name: 'Red',         hex: '#DC143C', category: 'PETG Basic' },
  { name: 'Pink',        hex: '#FF69B4', category: 'PETG Basic' },
  { name: 'Purple',      hex: '#7B2D8B', category: 'PETG Basic' },
  { name: 'Blue',        hex: '#1E6FCC', category: 'PETG Basic' },
  { name: 'Cyan',        hex: '#00BFFF', category: 'PETG Basic' },
  { name: 'Jade',        hex: '#00A36C', category: 'PETG Basic' },
  { name: 'Green',       hex: '#228B22', category: 'PETG Basic' },
  { name: 'Transparent', hex: '#E8F4F8', category: 'PETG Basic' },
  { name: 'Grey',        hex: '#808080', category: 'PETG Basic' },
  { name: 'Black',       hex: '#1A1A1A', category: 'PETG Basic' },

  // ── PETG HF (High Flow) ───────────────────────────────────────
  { name: 'White',       hex: '#F8F8F8', category: 'PETG HF' },
  { name: 'Yellow',      hex: '#FFD700', category: 'PETG HF' },
  { name: 'Orange',      hex: '#FF8C00', category: 'PETG HF' },
  { name: 'Red',         hex: '#DC143C', category: 'PETG HF' },
  { name: 'Pink',        hex: '#FF69B4', category: 'PETG HF' },
  { name: 'Purple',      hex: '#7B2D8B', category: 'PETG HF' },
  { name: 'Blue',        hex: '#1E6FCC', category: 'PETG HF' },
  { name: 'Cyan',        hex: '#00BFFF', category: 'PETG HF' },
  { name: 'Green',       hex: '#228B22', category: 'PETG HF' },
  { name: 'Transparent', hex: '#E8F4F8', category: 'PETG HF' },
  { name: 'Grey',        hex: '#808080', category: 'PETG HF' },
  { name: 'Black',       hex: '#1A1A1A', category: 'PETG HF' },

  // ── ABS ───────────────────────────────────────────────────────
  { name: 'White',       hex: '#F5F5F0', category: 'ABS' },
  { name: 'Beige',       hex: '#E8D8B0', category: 'ABS' },
  { name: 'Yellow',      hex: '#F0C800', category: 'ABS' },
  { name: 'Orange',      hex: '#D87000', category: 'ABS' },
  { name: 'Red',         hex: '#C01028', category: 'ABS' },
  { name: 'Blue',        hex: '#1850A0', category: 'ABS' },
  { name: 'Green',       hex: '#187018', category: 'ABS' },
  { name: 'Grey',        hex: '#787870', category: 'ABS' },
  { name: 'Dark Grey',   hex: '#484840', category: 'ABS' },
  { name: 'Black',       hex: '#1A1A1A', category: 'ABS' },

  // ── ASA ───────────────────────────────────────────────────────
  { name: 'White',       hex: '#F2F0EC', category: 'ASA' },
  { name: 'Yellow',      hex: '#E8C000', category: 'ASA' },
  { name: 'Orange',      hex: '#D06800', category: 'ASA' },
  { name: 'Red',         hex: '#B80C20', category: 'ASA' },
  { name: 'Blue',        hex: '#104890', category: 'ASA' },
  { name: 'Green',       hex: '#106010', category: 'ASA' },
  { name: 'Grey',        hex: '#707068', category: 'ASA' },
  { name: 'Black',       hex: '#141414', category: 'ASA' },

  // ── TPU 95A ───────────────────────────────────────────────────
  { name: 'White',       hex: '#F8F8F4', category: 'TPU 95A' },
  { name: 'Natural',     hex: '#F0E8D0', category: 'TPU 95A' },
  { name: 'Yellow',      hex: '#F8D800', category: 'TPU 95A' },
  { name: 'Orange',      hex: '#F07800', category: 'TPU 95A' },
  { name: 'Red',         hex: '#D01030', category: 'TPU 95A' },
  { name: 'Pink',        hex: '#E06898', category: 'TPU 95A' },
  { name: 'Blue',        hex: '#1868C0', category: 'TPU 95A' },
  { name: 'Cyan',        hex: '#00B0D0', category: 'TPU 95A' },
  { name: 'Green',       hex: '#20A030', category: 'TPU 95A' },
  { name: 'Grey',        hex: '#909088', category: 'TPU 95A' },
  { name: 'Black',       hex: '#181818', category: 'TPU 95A' },
  { name: 'Transparent', hex: '#E4EEF4', category: 'TPU 95A' },

  // ── Other ─────────────────────────────────────────────────────
  { name: 'White (PA)',  hex: '#F0EEE8', category: 'Other' },
  { name: 'Black (PA)',  hex: '#1A1A1A', category: 'Other' },
  { name: 'White (PC)',  hex: '#F5F4F0', category: 'Other' },
  { name: 'Black (PC)',  hex: '#1A1A1A', category: 'Other' },
  { name: 'PVA',         hex: '#F5EDD8', category: 'Other' },
  { name: 'HIPS',        hex: '#EEDDB8', category: 'Other' },
];

export function getDefaultFilaments(): FilamentColor[] {
  return COLOR_DEFS.map((def, i) => ({
    id: `default-${i}`,
    name: def.name,
    hex: def.hex,
    category: def.category,
    brand: DEFAULT_BRAND,
    count: 0,
    status: 'sealed' as const,
    isCustom: false,
  }));
}
